-- MySQL Script generated by MySQL Workbench
-- 11/05/14 21:05:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema productdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `productdb` ;

-- -----------------------------------------------------
-- Table `productdb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`Category` ;

CREATE TABLE IF NOT EXISTS `productdb`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  `CategoryParentId` INT NULL,
  `CategoryDescription` VARCHAR(200) NULL,
  PRIMARY KEY (`idCategory`),
  INDEX `fk_Category_Category_idx` (`CategoryParentId` ASC),
  CONSTRAINT `fk_Category_Category`
    FOREIGN KEY (`CategoryParentId`)
    REFERENCES `productdb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productdb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`Product` ;

CREATE TABLE IF NOT EXISTS `productdb`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(45) NOT NULL,
  `ProductCategoryId` INT NOT NULL,
  `ProductBarcode` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Category1_idx` (`ProductCategoryId` ASC),
  UNIQUE INDEX `ProductBarcode_UNIQUE` (`ProductBarcode` ASC),
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`ProductCategoryId`)
    REFERENCES `productdb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productdb`.`Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`Shop` ;

CREATE TABLE IF NOT EXISTS `productdb`.`Shop` (
  `idShop` INT NOT NULL AUTO_INCREMENT,
  `ShopName` VARCHAR(45) NOT NULL,
  `ShopAddress` VARCHAR(150) NOT NULL,
  `ShopLocation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idShop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productdb`.`Shop_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`Shop_has_Product` ;

CREATE TABLE IF NOT EXISTS `productdb`.`Shop_has_Product` (
  `Shop_idShop` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  `UnitPrice` DOUBLE NULL,
  `QuantityPrice` DOUBLE NULL,
  PRIMARY KEY (`Shop_idShop`, `Product_idProduct`),
  INDEX `fk_Shop_has_Product_Product1_idx` (`Product_idProduct` ASC),
  INDEX `fk_Shop_has_Product_Shop1_idx` (`Shop_idShop` ASC),
  CONSTRAINT `fk_Shop_has_Product_Shop1`
    FOREIGN KEY (`Shop_idShop`)
    REFERENCES `productdb`.`Shop` (`idShop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shop_has_Product_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `productdb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
